### ISSUE TITLE
同步报错

### ISSUE THREAD

**Issue by fwhappy** [okx/exchain#1004]
## 1. 详细描述

主网节点同步报错

## 3. exchaind版本号
v0.19.1

## 4. 日志

I[2021-09-02|02:58:50.863][24896] Interval<1164ms>, ApplyBlock<5150002>, tx<25>, elapsed<0ms>, validateBlock<0ms> module=main
error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected DBC62DB6E38E211BFCF82A96CCCEE5C98C42AC0DD10D733E386C096ACF58EE22, got F0AF8B8E9B498F68631DF986F69BD41A9F97A3FD436CAD709C97A470AD28EDCA

## 5. 网络
主网

**Comment by banishee** [comment]
https://forum.okt.club/d/197-5150000v0191
尝试按照这个步骤进行

**Comment by fwhappy** [comment]
v0.9.1 下载了新镜像，也有这个报错

Interval<516ms>, ApplyBlock<5158380>, tx<24>, elapsed<0ms>, validateBlock<0ms> module=main
error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected EC6D9CAE85D2B7CFED1947B946AB291DEC23BEFCA7405861E3BF22938767C013, got 01622720A9052684059F33F8BFAE17A13C264765DB70B8EE25A61BD9D7F9B13C

**Comment by banishee** [comment]
https://forum.okt.club/d/154
https://forum.okt.club/d/174
建议重新下载快照启动

**Comment by fwhappy** [comment]
不是快照的问题，我用的就是最新的快照
v0.19.1同步不了
我更新到v0.19.2这个pre-release版本后，同步可以继续
