### ISSUE TITLE
commit failed for application: error changing validator set: applying the validator changes would result in empty set

### ISSUE THREAD

**Issue by masayil** [okx/exchain#1125]
## 1. 详细描述
重启节点遇到了如下错误。
先出现了图片中的info，紧接着就发生error

## 2. 硬件配置
物理机 24C 128G SSD硬盘

## 3. exchaind版本号
v0.19.6.1

## 4. 日志
![ce911c7a18c95fb328c6bfa18d627f5](https://user-images.githubusercontent.com/65291464/139221472-64efb3d8-6c4e-4fba-8b2f-2e5ae8ddbd6d.png)
I[2021-10-28|16:47:08.343][2787319] starting ABCI with Tendermint                module=main
I[2021-10-28|16:47:22.822][2787319] Interval<14599ms>, ApplyBlock<6816165>, tx<230>, elapsed<907ms>, validateBlock<74ms>, abci<833ms>, validate<0ms>, updateState<0ms> module=main
error during handshake: error on replay: commit failed for application: error changing validator set: applying the validator changes would result in empty set
I[2021-10-28|16:47:23.985][2787351] starting ABCI with Tendermint                module=main
I[2021-10-28|16:47:38.663][2787351] Interval<14800ms>, ApplyBlock<6816165>, tx<230>, elapsed<921ms>, validateBlock<74ms>, abci<846ms>, validate<0ms>, updateState<0ms> module=main
error during handshake: error on replay: commit failed for application: error changing validator set: applying the validator changes would result in empty set
I[2021-10-28|16:47:39.038][2787393] starting ABCI with Tendermint                module=main
I[2021-10-28|16:47:53.638][2787393] Interval<14718ms>, ApplyBlock<6816165>, tx<230>, elapsed<1013ms>, validateBlock<72ms>, abci<940ms>, validate<0ms>, updateState<0ms> module=main
error during handshake: error on replay: commit failed for application: error changing validator set: applying the validator changes would result in empty set
I[2021-10-28|16:47:54.336][2787426] starting ABCI with Tendermint                module=main

## 5. 网络
测试网

**Comment by gazige** [comment]
+1

**Comment by masayil** [comment]
> +1

想去下最新的快照结果没有。。

**Comment by gazige** [comment]
> > +1
> 
> 想去下最新的快照结果没有。。

https://forum.okt.club/d/253-6816165leveldbrocksdb
