### ISSUE TITLE
Contract call blocked

### ISSUE THREAD

**Issue by soltrac** [okx/exchain#1303]
My address and contract has been bloked on the network. If I try to make a transaction I receive this message:

"address has been blocked".

What is the reason for this? I was arbitraging on the network, that I think is something legal. Who can I appeal this? I don't get, it is supposed to be a decentralized network....

**Comment by KamiD** [comment]
please leave your address

**Comment by soltrac** [comment]
My addresses are 

0x0AF564C3c06F70752Ea46ff19DdD4baD78f5E1ea
0xf8f181d466d44974257f9ccf0ce8398b7e059054

It is strange because other bots are liquidating positions also and have not been blocked.

**Comment by KamiD** [comment]
now your address is back to normal.

**Comment by soltrac** [comment]
Oh thank you very much for your help. I close this.
