### ISSUE TITLE
同步好慢啊，从昨天开始，，有人可以帮忙解决吗？ can not catch up with the latest height from yesterday 17/11 , who can help ?

### ISSUE THREAD

**Issue by jackie2022tec** [okx/exchain#2747]
## 1. 详细描述
同步好慢啊，从昨天开始，，有人可以帮忙解决吗？
can not catch up with the latest height from yesterday 17/11 , who can help ?

## 3. exchaind版本号
v1.6.5.1

## 4. 日志
I[2022-11-18|03:39:18.785][29] Height<15419716>, Tx<6>, BlockSize<4959>, GasUsed<112389354>, InvalidTxs<0>, RunTx<ApplyBlock<2256ms>, abci<1577ms>, saveResp<0ms>, persist<676ms>, mpUpdate<0ms>, saveState<0ms>>, MempoolTxs<0>, MempoolTxs[0], Iavl[getnode<387954>, rdb<76817>, rdbTs<4605ms>, savenode<68005>], DeliverTxs[RunAnte<1ms>, RunMsg<1569ms>, refund<0ms>]. module=main 
I[2022-11-18|03:39:24.471][29] Height<15419717>, Tx<6>, BlockSize<5050>, GasUsed<112389354>, InvalidTxs<0>, RunTx<ApplyBlock<5648ms>, abci<5027ms>, saveResp<0ms>, persist<620ms>, mpUpdate<0ms>, saveState<0ms>>, MempoolTxs<0>, MempoolTxs[0], Iavl[getnode<387267>, rdb<76748>, rdbTs<8749ms>, savenode<67807>], DeliverTxs[RunAnte<1ms>, RunMsg<5011ms>, refund<0ms>]. module=main 
I[2022-11-18|03:39:31.099][29] Height<15419718>, Tx<6>, BlockSize<5050>, GasUsed<112389354>, InvalidTxs<0>, RunTx<ApplyBlock<6065ms>, abci<5151ms>, saveResp<0ms>, persist<908ms>, mpUpdate<0ms>, saveState<0ms>>, MempoolTxs<0>, MempoolTxs[0], Iavl[getnode<388236>, rdb<76193>, rdbTs<13179ms>, savenode<67949>], DeliverTxs[RunAnte<0ms>, RunMsg<5121ms>, refund<0ms>]. module=main 
E[2022-11-18|03:39:34.878][29] dialing failed (attempts: 2): dial tcp 49.232.67.137:49736: i/o timeout. module=pex addr=1dbd8e4cd5e765b43db282378e420b08c33bf865@49.232.67.137:49736
I[2022-11-18|03:39:36.225][29] Height<15419719>, Tx<7>, BlockSize<13362>, GasUsed<113396402>, InvalidTxs<0>, RunTx<ApplyBlock<5091ms>, abci<4443ms>, saveResp<0ms>, persist<644ms>, mpUpdate<0ms>, saveState<0ms>>, MempoolTxs<0>, MempoolTxs[0], Iavl[getnode<388374>, rdb<77116>, rdbTs<8118ms>, savenode<68180>], DeliverTxs[RunAnte<0ms>, RunMsg<4422ms>, refund<0ms>]. module=main 
I[2022-11-18|03:39:41.545][29] MultiCache. module=main deleteMsg="Acc:Deleted Before:100489" nowStats="len(acc):90488 len(contracts):136 len(storage):2637391"
I[2022-11-18|03:39:45.896][29] Height<15419720>, Tx<6>, BlockSize<4956>, GasUsed<112389354>, InvalidTxs<0>, RunTx<ApplyBlock<9631ms>, abci<5274ms>, saveResp<0ms>, persist<4353ms>, mpUpdate<0ms>, saveState<0ms>>, MempoolTxs<0>, MempoolTxs[0], Iavl[getnode<387774>, rdb<76455>, rdbTs<8074ms>, savenode<67909>], DeliverTxs[RunAnte<0ms>, RunMsg<5249ms>, refund<0ms>]. module=main 

## 5. 网络
- [x] 主网

**Comment by cwbhhjl** [comment]
现在还慢吗，发一下你的机器配置，启动参数和当前同步到的高度

**Comment by fwhappy** [comment]
@cwbhhjl 

机器配置：8核16G
同步高度：Height<15441530>,
启动参数：
exchaind start --chain-id exchain-66 --db_backend rocksdb --mempool.sort_tx_by_gp --home /okex --pruning everything --max-open=10000 --disable-abci-query-mutex=1 --enable-bloom-filter=1 --mempool.size=10000 --mempool.recheck=0 --mempool.force_recheck_gap=2000 --close-mutex --iavl-enable-async-commit=true --iavl-cache-size=10000000 --mempool.max_gas_used_per_block=120000000 --fast-query=1 --enable-bloom-filter=1

同步非常慢

**Comment by cwbhhjl** [comment]
@fwhappy 你这个高度离负载比较低的高度还差十几个小时，同步到晚上的高度就会好很多了，如果不加机器配置的话，有两种选择
1. 继续同步，可能后面十小时范围的块会多花点时间，过去会好一些了，现在已经过了16个小时，我估计是不是至少已经同步到20号中午的块了？
2. 使用官方最新快照跳过昨天负载高的块 https://static.okex.org/cdn/oec/snapshot/index.html   看最新的状态是不是同步较快了

**Comment by fwhappy** [comment]
@cwbhhjl 使用最新的包之后，依旧很慢，大约10秒/区块，追不上的
看起来磁盘性能跟不上了，这个需要iops达到多少才可以？

**Comment by giskook** [comment]
@fwhappy 我们超级节点的吞吐量和IOPS：
节点吞吐量1000m   IOPS 16000

使用的版本  https://github.com/okex/exchain/releases/tag/v1.6.5.6
如何启动该版本参考
https://forum.okt.club/d/357

**Comment by fwhappy** [comment]
@giskook 感谢感谢

我现在运行的是v1.6.5.1, 先同步到v1.6.5.6试试看;

这个配置有点高，我先升级点iops试试看.

**Comment by fwhappy** [comment]
@giskook  @cwbhhjl 

修改了磁盘的iops到6000，看起来应该可以追上了

区块交易不是很多
但是感觉对cpu、内存、磁盘性能的要求比以前高了很多，8核32G的机器已经没法跑了
是新版本的原因吗

**Comment by cwbhhjl** [comment]
@fwhappy 请问你现在可以追上的最新配置是？

最近是主网 xen 项目上线导致区块里包含了很多脚本交易，执行这种交易成本比较高 https://www.oklink.com/en/okc/tx/0x65896AD838ED1A98ABE1232B3E3E5423DE21625333A1BB1BACCCD8A707F22AB0

**Comment by fwhappy** [comment]
m5.2xlarge
8 vCPU 32G
磁盘是gp3, 6000iops

这个配置可以缓慢的追上，iops还是100%
但是内存不够了，程序会out of memory导致崩溃
load average: 7.15, 6.76, 6.34 也是很高的

**Comment by cwbhhjl** [comment]
@fwhappy --iavl-cache-size=10000000 这个参数改小点比如 2000000 看看对内存有没有帮助

**Comment by fwhappy** [comment]
@cwbhhjl 我设置的1000000，还是out of memory，崩了

**Comment by giskook** [comment]
> @cwbhhjl 我设置的1000000，还是out of memory，崩了

@fwhappy 您可以按照文档 https://forum.okt.club/d/282-rocksdboom 设置下rocksdb的参数。

**Comment by fwhappy** [comment]
@giskook 

--rocksdb.opts max_open_files=100
参数设置成100，32GB内存的机器，还是会OOM

exchaind start --chain-id exchain-66 --db_backend rocksdb --mempool.sort_tx_by_gp --home /okex --pruning everything --max-open=1024 --rocksdb.opts max_open_files=100 --disable-abci-query-mutex=1 --enable-bloom-filter=1 --mempool.size=5000 --mempool.recheck=0 --mempool.force_recheck_gap=2000 --iavl-cache-size=1000000 --close-mutex

我这个启动参数还有什么可以优化的吗，主要是内存

**Comment by giskook** [comment]
> @giskook
> 
> --rocksdb.opts max_open_files=100 参数设置成100，32GB内存的机器，还是会OOM
> 
> exchaind start --chain-id exchain-66 --db_backend rocksdb --mempool.sort_tx_by_gp --home /okex --pruning everything --max-open=1024 --rocksdb.opts max_open_files=100 --disable-abci-query-mutex=1 --enable-bloom-filter=1 --mempool.size=5000 --mempool.recheck=0 --mempool.force_recheck_gap=2000 --iavl-cache-size=1000000 --close-mutex
> 
> 我这个启动参数还有什么可以优化的吗，主要是内存

hi @fwhappy ，
还有几个参数可以调低，您可以试下
1. 调低--commit-gap-height 参数
2. 调低--iavl-cache-size --iavl-fast-storage-cache-size参数
3. 使用tcmalloc https://forum.okt.club/d/341-rocksdb
4. 调低GOGC export GOGC=50

**Comment by cwbhhjl** [comment]
@fwhappy 请问现在是否还oom？

**Comment by fwhappy** [comment]
@cwbhhjl 
感谢各位帮忙，现在不oom了，但是同步偶尔会断开

这是我的参数
版本：1.6.5.8
go version go1.19.3 linux/amd64

 exchaind start --chain-id exchain-66 --db_backend rocksdb --mempool.sort_tx_by_gp --home /okex --pruning everything --max-open=1024 --rocksdb.opts max_open_files=100 --disable-abci-query-mutex=1 --enable-bloom-filter=1 --mempool.size=5000 --mempool.recheck=0 --mempool.force_recheck_gap=2000 --iavl-cache-size=500000 --iavl-fast-storage-cache-size=500000 --close-mutex --commit-gap-height=30

**Comment by fwhappy** [comment]
1.56 Txns/sec
这么少的交易量，8核32G的机器感觉已经不能跑了

**Comment by xiangjianmeng** [comment]
> 1.56 Txns/sec 这么少的交易量，8核32G的机器感觉已经不能跑了

不能只看交易量，xen项目导致每个交易的gasUsed很大，所以要看一个区块的gasUsed更能准确反映执行一个区块内存和IO的负载。
