### ISSUE TITLE
rpc response with "Method not found"

### ISSUE THREAD

**Issue by wooyeeyii** [okx/exchain#2781]
## 1. 详细描述
root@cf1c1371648f:/# curl -X POST 'http://127.0.0.1:26657' -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0","method": "eth_blockNumber","params": [],"id": 1}'
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32601,
    "message": "Method not found"
  }
}

rest api is normal(curl http://127.0.0.1:26659/exchain/v1/node_info)

## 2. 硬件配置
configuration: 
[2022-11-21|14:42:57.203][7] All flags:
         rest.application_name                        =
        rest.external_laddr                          = 127.0.0.1:26659
        rest.laddr                                   = tcp://0.0.0.0:26659
        rest.nacos_namespace_id                      =
        rest.nacos_urls                              =
        rest.path_prefix                             = exchain
        rest.unlock_key                              =
        rest.unlock_key_home                         = /root/.exchaincli
        rocksdb.opts                                 =
        rpc-block-cache                              = 30000
        rpc-tx-cache                                 = 100000
        rpc.cors_allowed_headers                     = [Origin Accept Content-Type X-Requested-With X-Server-Time]
        rpc.cors_allowed_methods                     = [HEAD GET POST]
        rpc.cors_allowed_origins                     = [*]
        rpc.disable-api                              =
        rpc.enable-monitor                           = false
        rpc.enable-multi-call                        = false
        rpc.external_laddr                           = 127.0.0.1:26657
        rpc.grpc_laddr                               =
        rpc.grpc_max_open_connections                = 900
        rpc.laddr                                    = tcp://0.0.0.0:26657
        rpc.logs-limit                               = 0
        rpc.logs-timeout                             = 60
        rpc.max_body_bytes                           = 1000000
        rpc.max_header_bytes                         = 1048576
        rpc.max_open_connections                     = 900
        rpc.max_subscription_clients                 = 100
        rpc.max_subscriptions_per_client             = 1000
        rpc.rate-limit-api                           =
        rpc.rate-limit-burst                         = 1
        rpc.rate-limit-count                         = 0
        rpc.timeout_broadcast_tx_commit              = 10s
        rpc.tls_cert_file                            =
        rpc.tls_key_file                             =
        rpc.tmrpc_application_name                   =
        rpc.tmrpc_nacos_namespace_id                 =
        rpc.tmrpc_nacos_urls                         =
        rpc.unsafe                                   = false

## 3. exchaind版本号
  exchaind version
v1.6.5.6

## 5. 网络
- [x] 主网

**Comment by cwbhhjl** [comment]
eth rpc api:  http://127.0.0.1:26659

curl -X POST 'http://127.0.0.1:26659/' -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0","method": "eth_blockNumber","params": [],"id": 1}'

**Comment by wooyeeyii** [comment]
> eth rpc api: http://127.0.0.1:26659
> 
> curl -X POST 'http://127.0.0.1:26659/' -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0","method": "eth_blockNumber","params": [],"id": 1}'

thx a lot
