### ISSUE TITLE
How do I turn on the trace related API interface?

### ISSUE THREAD

**Issue by YuXiaoCoder** [okx/exchain#3258]
How can I use the debug_traceBlockByNumber or debug_traceTransaction interfaces similar to GETH RPC?

**Comment by giskook** [comment]
@YuXiaoCoder 
Please add `--debug-api=true` and make sure `--pruning=nothing` when start your node. Then have a try.

**Comment by YuXiaoCoder** [comment]
@giskook That's fine. Thank you.
To help those who come after me, here's an example of my command:
```bash
/opt/oktmain/core/exchaind start --node-mode=archive --chain-id=exchain-66 --home=/mnt/oktmain/node --rest.laddr=tcp://0.0.0.0:26659 --mempool.sort_tx_by_gp --rocksdb.opts max_open_files=1024 --debug-api=true --pruning=nothing --fast-query=false
```
