### ISSUE TITLE
How to solve the problem of synchronization in test network?

### ISSUE THREAD

**Issue by yiyang518** [okx/exchain#3279]
![image](https://github.com/okx/exchain/assets/49931274/bb265c28-8136-4cb0-b2f0-cfa22d77e12d)

Not even after repairing the status data
V1.7.0  V1.7.0.3  Both versions reported errors

**Comment by giskook** [comment]
Please refer to https://forum.okt.club/d/218

**Comment by yiyang518** [comment]
> 请参考https://forum.okt.club/d/218
Have no effect

**Comment by giskook** [comment]
> > 请参考https://forum.okt.club/d/218
> > Have no effect

Please try to repair with v1.8.0 https://github.com/okx/exchain/releases/tag/v1.8.0

**Comment by yiyang518** [comment]
> > > 请参考https://forum.okt.club/d/218
> > > 没有效果
> 
> 请尝试使用 v1.8.0 修复https://github.com/okx/exchain/releases/tag/v1.8.0

Thank you, the problem is solved.
