### ISSUE TITLE
[Dex] internal undefined Response when send MsgUpdateOperator by both okexchaincli and gosdk

### ISSUE THREAD

**Issue by RevelationOfTuring** [okx/exchain#463]
### 1. Describe
Internal undefined Response when send MsgUpdateOperator by both okexchaincli and gosdk

okexchain tag：release/v0.15.0
### 3. Recover
1. register Dex Operator first;
2. send MsgUpdateOperator：
```shell
okexchaincli tx dex edit-operator --handling-fee-address okexchain193xnjknz3e52mqv2nyufnzjugu3mh65rpxdasn --website www.okex.com --from turing -y -b block
{
  "height": "0",
  "txhash": "1F03F42463A65FF9C9726AA801A57E7387EF54BF0AD75C0F4F3FB6D1BAFF3E97",
  "codespace": "undefined",
  "code": 1,
  "raw_log": "internal"
}
```

## Version

release/v0.15.0
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tianxiataiping** [comment]
Loopback Testing Pass
-- | --
