### ISSUE TITLE
[Farm] undefined codespace in returned TxResponse when farm proposal failed to be submitted

### ISSUE THREAD

**Issue by RevelationOfTuring** [okx/exchain#467]
### 1. Describe

okexchaincli tx gov submit-proposal manage-white-list manage_white_list_proposal.json --from turing -y -b block

```shell
{
  "height": "7",
  "txhash": "64F4FFDD7F1770C150F0C1B4DC0EF94BEB126449C32CBC1811A8A060C8BF8370",
  "codespace": "undefined",
  "code": 1,
  "raw_log": "internal",
  "gas_wanted": "200000",
  "gas_used": "64338"
}
```

### 3. Recover
```shell
okexchaincli tx farm create-pool pool1 1tokt tokt --from turing -y -b block

okexchaincli tx gov submit-proposal manage-white-list manage_white_list_proposal.json --from turing -y -b block
```

## Expected Result

It's expected to return the error with message `failed. token xxx does not exist`.

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tianxiataiping** [comment]
loopback testing pass
