### ISSUE TITLE
undefined error msg when edit validator msg was sent by the one who never creates validators

### ISSUE THREAD

**Issue by RevelationOfTuring** [okx/exchain#478]
## Summary of Bug
commit：76a1a5c290868e272ca53b885ab47168b719743b
### 3. Recover
NOTE: user `test` has never created validator.
```shell
okexchaincli tx staking edit-validator --website "okex.com" --from test -y -b block 
```
```
{
  "height": "35701",
  "txhash": "0F1096EABB7D6AD681C15D007BD90644FC59B7B4814944ED75C65370D30824F3",
  "codespace": "undefined",
  "code": 1,
  "raw_log": "internal",
  "gas_wanted": "200000",
  "gas_used": "57651"
}
```

## Expected Result
context like:
```
"validator xxx does not exist"
```

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by refix21** [comment]
I have a problem when transferring the money. The transfer was done, but I do not know where it went. What happened to me? Can you help?

أُرسلت من بلال

**Comment by RevelationOfTuring** [comment]
> I have a problem when transferring the money. The transfer was done, but I do not know where it went. What happened to me? Can you help? أُرسلت من بلال
> […](#)
> ‫في 08‏/12‏/2020 الساعة 10:40 ص، كتب/كتبت ‏MichaelWang ***@***.***>:‬ ﻿ Summary of Bug commit：76a1a5c290868e272ca53b885ab47168b719743b 1. Describe 2. Impact 3. Recover NOTE: user test has never created validator. okexchaincli tx staking edit-validator --website "okex.com" --from test -y -b block { "height": "35701", "txhash": "0F1096EABB7D6AD681C15D007BD90644FC59B7B4814944ED75C65370D30824F3", "codespace": "undefined", "code": 1, "raw_log": "internal", "gas_wanted": "200000", "gas_used": "57651" } Expected Result Version Steps to Reproduce For Admin Use Not duplicate issue Appropriate labels applied Appropriate contributors tagged Contributor assigned/self-assigned — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Of course. Can you show out your command input when u transferred?

**Comment by tianxiataiping** [comment]
loopback testing pass

**Comment by refix21** [comment]
اطلع على هذا التطبيق المجاني، ستحقق أرباحًا من خلاله مقابل المشي 🚶 https://sweatco.in/i/bilo463384


أُرسلت من بلال
