### ISSUE TITLE
unmarshal error occurred on the supply of a specific token query

### ISSUE THREAD

**Issue by RevelationOfTuring** [okx/exchain#484]
### 3. Recover
```shell
okexchaincli query supply total tokt -o json
```
or
```shell
okexchaincli query supply total tokt -o text
```

error msg:
```
ERROR: math/big: cannot unmarshal "2000120.500000000000000000" into a *big.Int
```
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tianxiataiping** [comment]
loopback testing pass
