### ISSUE TITLE
evm  tx nonce bug 

### ISSUE THREAD

**Issue by ChainCoderX** [okx/exchain#538]
This is a bug.

	seq := acc.GetSequence()
	// if multiple transactions are submitted in succession with increasing nonces,
	// all will be rejected except the first, since the first needs to be included in a block
	// before the sequence increments
	if msgEthTx.Data.AccountNonce < seq {
		return ctx, sdkerrors.Wrapf(
			sdkerrors.ErrInvalidSequence,
			"invalid nonce; got %d, expected %d", msgEthTx.Data.AccountNonce, seq,
		)
	}

**Comment by ChainCoderX** [comment]
everyone can replay the  old txs, right ?

**Comment by summerpro** [comment]
Yes, this bug was also discovered last week and has been submitted to the ethermint project, [link](https://github.com/cosmos/ethermint/issues/686)

**Comment by summerpro** [comment]
* @wade-liwei Thank you for your discovery, this bug has been fixed.
* ethermint [pr](https://github.com/cosmos/ethermint/pull/692)
* okexchain [pr](https://github.com/okex/okexchain/pull/544)
