### ISSUE TITLE
Error when starting rest-server

### ISSUE THREAD

**Issue by angelorc** [okx/exchain#561]
### 1. Describe

I installed okexchan v0.16.1 with golang v1.14.x, when I try to start the rest server I get an error

### 2. Impact

Can't start the rest server

### 3. Recover

Still offline

## Expected Result
The rest server should start

## Version
v0.16.1

## Steps to Reproduce
okexchaincli rest-server

panic: failed to subscribe pending txs: client is not running. Use .Start() method to start

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zhongqiuwood** [comment]
please use [okexchaind start --rest.laddr] instead.
```
okexchaind start -h

      --rest.laddr string                                The address for the rest-server to listen on. (0.0.0.0:0 means any interface, anyport) (default "tcp://0.0.0.0:26659")
```

**Comment by angelorc** [comment]
Thanks
