### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by beride** [okx/exchain#564]
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by beride** [comment]
dial tcp 172.217.24.17:443: i/o

Get "https://proxy.golang.org/github.com/%21comcast/pulsar-client-go/@v/v0.1.1.mod": dial tcp 172.217.24.17:443: i/o timeout

**Comment by RevelationOfTuring** [comment]
@beride Hi, you may try it with proxy.

```shell
export GO111MODULE=on
export GOPROXY="https://goproxy.io"
make install
```
