### ISSUE TITLE
Can not connect to node

### ISSUE THREAD

**Issue by Wangmmx** [okx/exchain#565]
I can't connect to the node in your document: https://www.okex.com/okexchain/v1/accounts/okexchain1v8segh8mlw297s2ksy6pp6nwxn3el0wm3hts9x

What are the rpc nodes of the main network and test network?

**Comment by RevelationOfTuring** [comment]
@Wangmmx Hi , the node rpc info:
mainnet: tcp://13.231.209.76:26657
testnet: tcp://35.176.62.211:26657

**Comment by Wangmmx** [comment]
Thanks for your reply!
Is it the TCP interface? Can all the methods in the document be called? Can I use https? I tried it and reported an error

```
var options = {
    'method': 'GET',
    'url': 'https://13.231.209.76:26657/okexchain/v1/accounts/okexchain1c59l52a8a73fsfwa8gr3xnru7272xq389wt2e4',
    'headers': {
    }
};
request(options, function (error, response) {
    if (error) throw new Error(error);
    console.log(response.body);
});
```
Error: write EPROTO 4535371200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

When I use
```
    'url': 'tcp://13.231.209.76:26657/okexchain/v1/accounts/okexchain1c59l52a8a73fsfwa8gr3xnru7272xq389wt2e4',

```
Error: Error: Invalid protocol: tcp:

**Comment by RevelationOfTuring** [comment]
@Wangmmx
`https://www.okex.com/okexchain/v1/accounts/okexchain1v8segh8mlw297s2ksy6pp6nwxn3el0wm3hts9x` depends on the REST. u can try rpc with `okexchaincli`.

just like:
```shell
okexchaincli query account okexchain1c59l52a8a73fsfwa8gr3xnru7272xq389wt2e4 --node tcp://13.231.209.76:26657
```

**Comment by Wangmmx** [comment]
Oh, I understand what you mean. I need to assemble transaction body and other information, and I hope it can be called using the http REST interface. Now the examples in the document are not available, right? Is there a http url available?

**Comment by Wangmmx** [comment]
I still have an issue that talks about part of the transaction body. No one has replied yet. If possible, can you please help me take a look or assign someone? Thanks a lot! 
https://github.com/okex/okexchain-javascript-sdk/issues/38

**Comment by RevelationOfTuring** [comment]
> Oh, I understand what you mean. I need to assemble transaction body and other information, and I hope it can be called using the http REST interface. Now the examples in the document are not available, right? Is there a http url available?

The url is avaliable but the address doesn't exist on the OKExChain mainnet. You can try an address holding coins like:
`https://www.okex.com/okexchain/v1/accounts/okexchain1vegcudd5ypa6j025w4tf6hspt0vr27tynm03uf`

**Comment by Wangmmx** [comment]
The node cannot be connected, an error will be reported.
`  Error: Error: connect ETIMEDOUT 104.244.46.93:443`
The same as using curl
```
curl --location --request GET 'https://www.okex.com/okexchain/v1/accounts/okexchain1vegcudd5ypa6j025w4tf6hspt0vr27tynm03uf'
curl: (7) Failed to connect to www.okex.com port 443: Operation timed out
```
By the way, under the correct connection, the account will return correctly if there is no currency, but an empty array will be returned under the currency, no error will be reported.

**Comment by RevelationOfTuring** [comment]
> I still have an issue that talks about part of the transaction body. No one has replied yet. If possible, can you please help me take a look or assign someone? Thanks a lot!
> [okex/okexchain-javascript-sdk#38](https://github.com/okex/okexchain-javascript-sdk/issues/38)

OK. Someone will check it. Thx for ur feedback.

**Comment by RevelationOfTuring** [comment]
> The node cannot be connected, an error will be reported.
> ` Error: Error: connect ETIMEDOUT 104.244.46.93:443`
> The same as using curl
> 
> ```
> curl --location --request GET 'https://www.okex.com/okexchain/v1/accounts/okexchain1vegcudd5ypa6j025w4tf6hspt0vr27tynm03uf'
> curl: (7) Failed to connect to www.okex.com port 443: Operation timed out
> ```
> 

alternative：https://www.okexcn.com/okexchain/v1/accounts/okexchain1vegcudd5ypa6j025w4tf6hspt0vr27tynm03uf

**Comment by Wangmmx** [comment]
> > The node cannot be connected, an error will be reported.
> > ` Error: Error: connect ETIMEDOUT 104.244.46.93:443`
> > The same as using curl
> > ```
> > curl --location --request GET 'https://www.okex.com/okexchain/v1/accounts/okexchain1vegcudd5ypa6j025w4tf6hspt0vr27tynm03uf'
> > curl: (7) Failed to connect to www.okex.com port 443: Operation timed out
> > ```
> > 
> > 
> > By the way, under the correct connection, the account will return correctly if there is no currency, but an empty array will be returned under the currency, no error will be reported.
> 
> alternative：https://www.okexcn.com/okexchain/v1/accounts/okexchain1vegcudd5ypa6j025w4tf6hspt0vr27tynm03uf

This one is work, so I should use www.okexcn.com instead of www.okex.com, right?

**Comment by RevelationOfTuring** [comment]
> This one is work, so I should use www.okexcn.com instead of www.okex.com, right?

www.okex.com is recommended if u have proxy. www.okexcn.com is just an alternative domain for it.

**Comment by Wangmmx** [comment]
Ok I got it, Thanks for all reply! It helped a lot, and close the issue
