### ISSUE TITLE
error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by wo4zhuzi** [okx/exchain#567]
According to the document to install. start failure error is as follows. how to solve. thank you:

![image](https://user-images.githubusercontent.com/20334885/104904560-4158e280-59bc-11eb-9bdd-5ab11a5fc5d0.png)

**Comment by RevelationOfTuring** [comment]
@wo4zhuzi hi, are you going to start a local net or join to the testnet of OKExChain? You'd better follow the docs below step by step.

Deploy your local net : https://okexchain-docs.readthedocs.io/en/latest/getting-start/deploy-you-own-okexchain-testnet.html
Join OKExChain testnet: https://okexchain-docs.readthedocs.io/en/latest/getting-start/join-okexchain-testnet.html

**Comment by wo4zhuzi** [comment]
> @wo4zhuzi hi, are you going to start a local net or join to the testnet of OKExChain? You'd better follow the docs below step by step.
> 
> Deploy your local net : https://okexchain-docs.readthedocs.io/en/latest/getting-start/deploy-you-own-okexchain-testnet.html
> Join OKExChain testnet: https://okexchain-docs.readthedocs.io/en/latest/getting-start/join-okexchain-testnet.html


I think I know the reason and hope to help people who have the same problem.
Execute the following command:

```
okexchaind unsafe-reset-all
```
