### ISSUE TITLE
How to calculate txHash by transaction body?

### ISSUE THREAD

**Issue by Wangmmx** [okx/exchain#572]
I want to know how to calculate txHash, it means to get txHash before send the tx.
Could you Please help me? Thanks

**Comment by RevelationOfTuring** [comment]
> I want to know how to calculate txHash, it means to get txHash before send the tx.
> Could you Please help me? Thanks

@Wangmmx Hi~

It's better to focus on the method `func (tx Tx) Hash() []byte` in `okex/tendermint@v0.33.9-okexchain1/types/tx.go line 22`.

I think you should encode your tx first as the way like : `okex/cosmos-sdk@v0.39.2-okexchain2/x/auth/client/utils/tx.go line 97`
```go
func CompleteAndBroadcastTxCLI(txBldr authtypes.TxBuilder, cliCtx context.CLIContext, msgs []sdk.Msg) error {
	...

	// check how to build a "txBytes"
	txBytes, err := txBldr.BuildAndSign(fromName, keys.DefaultKeyPass, msgs)
	if err != nil {
		return err
	}

        ...
}

```

**Comment by Wangmmx** [comment]
Yes, I did cosmos transfer before, and I need to encode it before calculation. Cosmos has an encode interface, but I didn’t find the relevant interface on OKT, I will check the code you mentioned first. Thanks for the reply

**Comment by Wangmmx** [comment]
> > I want to know how to calculate txHash, it means to get txHash before send the tx.
> > Could you Please help me? Thanks
> 
> @Wangmmx Hi~
> 
> It's better to focus on the method `func (tx Tx) Hash() []byte` in `okex/tendermint@v0.33.9-okexchain1/types/tx.go line 22`.
> 
> I think you should encode your tx first as the way like : `okex/cosmos-sdk@v0.39.2-okexchain2/x/auth/client/utils/tx.go line 97`
> 
> ```go
> func CompleteAndBroadcastTxCLI(txBldr authtypes.TxBuilder, cliCtx context.CLIContext, msgs []sdk.Msg) error {
> 	...
> 
> 	// check how to build a "txBytes"
> 	txBytes, err := txBldr.BuildAndSign(fromName, keys.DefaultKeyPass, msgs)
> 	if err != nil {
> 		return err
> 	}
> 
>         ...
> }
> ```

Is there an encode interface or sdk method? What you said is the source code of Go, I can’t call it directly with nodejs

**Comment by RevelationOfTuring** [comment]
Sorry we dont get that tool in our jssdk but you can try `okexchaincli tx encode [file]` to encode tx locally. Maybe you can check the logic in jssdk before tx broadcasting and fit it to what you want.

**Comment by Wangmmx** [comment]
> Sorry we dont get that tool in our jssdk but you can try `okexchaincli tx encode [file]` to encode tx locally. Maybe you can check the logic in jssdk before tx broadcasting and fit it to what you want.

Could you please add a similar interface? Cosmos has such an interface call `txs/encode`, I did it according to Cosmos, I really need this for currency support

**Comment by RevelationOfTuring** [comment]
> > Sorry we dont get that tool in our jssdk but you can try `okexchaincli tx encode [file]` to encode tx locally. Maybe you can check the logic in jssdk before tx broadcasting and fit it to what you want.
> 
> Could you please add a similar interface? Cosmos has such an interface call `txs/encode`, I did it according to Cosmos, I really need this for currency support

I checked that OKExChain supports `/txs/encode` rest routes too. You can try it.
```
https://www.okex.com/okexchain/v1/txs/encode

https://www.okexcn.com/okexchain/v1/txs/encode
```

**Comment by Wangmmx** [comment]
Ok!!! The full url is https://www.okexcn.com/okexchain/v1/txs/encode? Thanks a lot!

**Comment by RevelationOfTuring** [comment]
> Ok!!! The full url is https://www.okexcn.com/okexchain/v1/txs/encode? Thanks a lot!

Yup, the same usage  as cosmos.

**Comment by Wangmmx** [comment]
> > Ok!!! The full url is https://www.okexcn.com/okexchain/v1/txs/encode? Thanks a lot!
> 
> Yup, the same usage as cosmos.

Thanks for the reply! The encode api is work, thanks again

Finally, I would like to ask about the fee. Is the current fee fixed? If it is not fixed, how to calculate fee?

**Comment by RevelationOfTuring** [comment]
> Finally, I would like to ask about the fee. Is the current fee fixed? If it is not fixed, how to calculate fee?

there are two ways to pay fees on okexchaincli:
1. give out the fees/gas directly：`okexchaincli tx .... --fees 0.02okt --gas 200000`. 0.02okt can cover most txs' consumption.
2. give out the gas-price / gas/ gas-adjustment: `okexchaincli tx .... --gas-prices 0.000000001okt --gas-adjustment 1.1  --gas 200000`.

Note:
If you dont show `gas` explicitly, it will be set to `200000` as default.

Above all,  the first is recommended.

**Comment by Wangmmx** [comment]
Ok, I wrote the fixed fee directly in the transaction body as 0.02okt, isn't the decimal of OKT 18? The precision in the transaction body is 18

![image](https://user-images.githubusercontent.com/22836587/105316912-7f444980-5bfc-11eb-998e-b3a373d2e801.png)

**Comment by RevelationOfTuring** [comment]
> Ok, I wrote the fixed fee directly in the transaction body as 0.02okt, isn't the decimal of OKT 18? The precision in the transaction body is 18
 
OKT's precision is 18 . 

`okexchaincli` will  convert string `0.02okt` to the valid decimal amount with 18 precision implicitly.

**Comment by Wangmmx** [comment]
Okay, thank you for your patient reply! Closing the issue

**Comment by RevelationOfTuring** [comment]
> Okay, thank you for your patient reply! Closing the issue

my plessure
