### ISSUE TITLE
start mainnet，occur “error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain”

### ISSUE THREAD

**Issue by msdn129** [okx/exchain#576]
### 1. Describe

The okexchain is made install succeed according to the help Doc. when I attempt to join main net,  meet above prompt information.  what should I do to pass this step,  or what information or knowledgement should I study to solve this problem? 

Thanks

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by wo4zhuzi** [comment]
I've had the same problem, the solution:

1. Replacement genesis.json by
[ https://raw.githubusercontent.com/okex/mainnet/main/genesis.json ]( https://raw.githubusercontent.com/okex/mainnet/main/genesis.json )

```
cd /root/.okexchaind/config
rm genesis.json
wget https://raw.githubusercontent.com/okex/mainnet/main/genesis.json 
```


2. If the error is still reported, continue to execute

```

okexchaind unsafe-reset-all

```

Hope to help you

**Comment by msdn129** [comment]
thanks for your help,run succeed.
