### ISSUE TITLE
How to get tokens currency accuracy

### ISSUE THREAD

**Issue by wo4zhuzi** [okx/exchain#577]
I know the accuracy of OKT is 18. What about other tokens?
How do I get it.

**Comment by RevelationOfTuring** [comment]
> I know the accuracy of OKT is 18. What about other tokens?

@wo4zhuzi Hi~
All OIP10 tokens' accuracy is 18. It's possible to define that in OIP20 token when evm of OKExChain is open as the way of ERC20.

**Comment by wo4zhuzi** [comment]
> > I know the accuracy of OKT is 18. What about other tokens?
> 
> @wo4zhuzi Hi~
> All OIP10 tokens' accuracy is 18. It's possible to define that in OIP20 token when evm of OKExChain is open as the way of ERC20.

Well, thank you
