### ISSUE TITLE
How can I get OKTs?

### ISSUE THREAD

**Issue by Wangmmx** [okx/exchain#581]
For now, the Okex exchange can not withdraw, and I need to test transfer OKT function, I saw several transactions in https://www.oklink.com/okexchain, where did they get the coins? 

I want to buy some to test, can you please send some OKT to test? Or  how can I get testnet coins?

**Comment by zhongqiuwood** [comment]
Access https://www.okexcn.com/drawdex for testnet tokens.

**Comment by Wangmmx** [comment]
> Access https://www.okexcn.com/drawdex for testnet tokens.

Thanks, I have got mainNet OKT and transfer it successfully, closing this issue
