### ISSUE TITLE
Bug when try to recover key from mnemonic

### ISSUE THREAD

**Issue by angelorc** [okx/exchain#584]
## Summary of Bug
I found a bug when try to recover key from mnemonic
### 1. Describe

`okexchaincli keys add test --recover`
### 2. Impact

Cannot import mnemonic from `cli`
### 3. Recover

///
## Expected Result
Should recover key from mnemonic

## Version
v0.16.1

## Steps to Reproduce
`okexchaincli keys add test --recover`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
@angelorc  Hi~

The right way is `okexchaincli keys add test --recover -m "your mnemonics"`
