### ISSUE TITLE
提币失败

### ISSUE THREAD

**Issue by 520guanyu** [okx/exchain#599]
提币时，广播调用 rpc api：`https://www.okex.com/okexchain/v1/txs`,      response: `unauthorized: signature verification failed; verify correct account sequence and chain-id` .     rpc url : `https://www.okex.com/okexchain/v1`     chain-id: `okexchain-66`.   能帮忙确认是什么原因吗？ 感谢！
![image](https://user-images.githubusercontent.com/37165196/105844000-76e07a00-6013-11eb-8b68-f061859701d3.png)
{"height":"0","txhash":"0E8E791C39767FDEE9AC0B5E0F42A9318BDB2318952EEE12618814C3C1F0A3E2","code":4,"raw_log":"unauthorized: signature verification failed; verify correct account sequence and chain-id"}

**Comment by RevelationOfTuring** [comment]
@520guanyu Hi~

Please focus on the process of cold signature offline with the right `account number` and `sequence number`.
