### ISSUE TITLE
okexchaincli rest-server not running 

### ISSUE THREAD

**Issue by hufengvia** [okx/exchain#600]
my okexchain version is v0.16.2, and the okexchaind running normally the rpc address is tpc://localhost:26657, and then I need to run to okexchaincli rest-server , and my param is : 

```
okexchaincli rest-server --chain-id=okexchain-65 --laddr=tcp://0.0.0.0:3313 --node=tcp://localhost:26657 --trust-node=true --home=/data/okex
```

and the return is a panic : 
```
panic: failed to subscribe pending txs: client is not running. Use .Start() method to start

goroutine 66 [running]:
github.com/okex/okexchain/app/rpc/namespaces/eth/filters.(*EventSystem).eventLoop(0xc0004f5f80)
	/root/okexchain/app/rpc/namespaces/eth/filters/filter_system.go:297 +0x1758
created by github.com/okex/okexchain/app/rpc/namespaces/eth/filters.NewEventSystem
	/root/okexchain/app/rpc/namespaces/eth/filters/filter_system.go:88 +0x38d
```

**Comment by RevelationOfTuring** [comment]
@hufengvia Hi~
Rest server will be started with the running of node(`okexchaind start`) and the function `okexchaincli rest-server` is not available  now.

**Comment by hufengvia** [comment]
> node

hello , I see that , but my node  and my node start by : 
```
okexchaind start --chain-id okexchain-65 --log_file /var/log/okexchain/okexchain.log --home /data/okex --rest.laddr tcp://0.0.0.0:3313
```
and the node running normally , but when I use the rest api like this : 
```
curl --location --request GET 'http://localhost:3313/blocks/latest'
```

I got an error : 
```
404 page not found
```

why is that ? this api path is found in your docs.

**Comment by hufengvia** [comment]
thanks , I solve this issue!
