### ISSUE TITLE
some rest api return err

### ISSUE THREAD

**Issue by hufengvia** [okx/exchain#603]
my rest api running normally , when I use : 
```
curl --location --request GET 'http://localhost:3313/okexchain/v1/accounts/okexchain1fqjphugnf0uyjkgqxa5vg946wcjld7n5y4ql0q/orders?page=1&per_page=2'
```

it return ：
```
{"code":62008,"msg":"Backend Plugin's Not Enabled","detail_msg":"Backend Plugin's Not Enabled","data":null}
```

and how to enable the backend? I did not see this in the docs.

**Comment by banishee** [comment]
you have to start okexchaind with the flag `--backend.enable_backend`

**Comment by hufengvia** [comment]
> you have to start okexchaind with the flag `--backend.enable_backend`

ok thanks ~
