### ISSUE TITLE
evm rpc bug

### ISSUE THREAD

**Issue by hufengvia** [okx/exchain#619]
### 1. Describe
when I use the method "eth_getBlockByNumber" of block 596894 (0x91b9e), and then I got return , the block hash is:0x50875260f54f2ae2537761e28cc8b4c40efbae413eb7c4c5f9467dd3061daf13; but is not the same as the blockchain explorer hash , and the I use eth_getLogs to get the block 596894's logs according to the block hash ,return err:
`
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"{\"code\":1,\"log\":\"internal\",\"height\":597162,\"codespace\":\"undefined\"}"}}
`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by KamiD** [comment]
nice catch, this issue was fixed in pr #622
