### ISSUE TITLE
transaction failed in Metamask, but succeed on chain

### ISSUE THREAD

**Issue by realeliza-official** [okx/exchain#645]
### 1. Describe

部署 Uniswap 的Factory 和 Router 到测试链，添加流动性以后。使用Pair的transfer方法转账LP Token时，有时成功，有时失败。

比如成功的交易

https://www.oklink.com/okexchain-test/tx/0x901cbd9281c08f24488f1e55f6c784fe422dc7f51f1f0ca5ffa8c09402816f86

会显示代币转移。

浏览器显示成功而在Metamask显示失败的交易

https://www.oklink.com/okexchain-test/tx/0xa81a87bed72d20dcb364f3494ea801ab8d56918caffbc44d8465c13c03a7b241

没有代币的转移。不过虽然没有显示代币的转移，两边的余额也都发生了变化，发送者扣了余额，接收者增加了余额。

在Remix里显示：

```

status | false Transaction mined but execution failed
-- | --
transaction hash | 0xa81a87bed72d20dcb364f3494ea801ab8d56918caffbc44d8465c13c03a7b241
from | 0x64D93A001DaC5feC6ADdB79A4D6e96969d704958
to | 0x0Dd4312dE0015Ae09ee57cD06a3D17A7B72cdDA7 0x0Dd4312dE0015Ae09ee57cD06a3D17A7B72cdDA7
gas | 86520 gas
transaction cost | 28945 gas
hash | 0xa81a87bed72d20dcb364f3494ea801ab8d56918caffbc44d8465c13c03a7b241
input | 0xa90...da000
decoded input | -
decoded output | -
value | 0 wei


```

## Steps to Reproduce

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by KamiD** [comment]
has been resolved
