### ISSUE TITLE
support debug_traceTransaction interface

### ISSUE THREAD

**Issue by heipacker** [okx/exchain#714]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
Hi ~ @heipacker

Thanks for your demand of OKExChain. There are so many tasks with high priority for our team right now and the demand will be listed later.

**Comment by JpSub7** [comment]
[Jpsub7@JpSub7](://github.com/TP-Lab/tp-android)

**Comment by JpSub7** [comment]
PrivacyXporter Inc'MSingnitePrivacySinSign

**Comment by JpSub7** [comment]
`PrivacyXporter-sinsigncert`

**Comment by JpSub7** [comment]
- HOSTKIO KIO

**Comment by JpSub7** [comment]
<0x1F573D6Fb3F13d689FF844B4cE37794d79a7FF1C>

**Comment by KamiD** [comment]
the interface of debug_traceTransaction has been supported on okc already
