### ISSUE TITLE
Please provide an api / util function to compute okChainTxHash given raw tx byte[]

### ISSUE THREAD

**Issue by dryruner** [okx/exchain#783]
## Summary
Please provide an api or util function to compute okexchain TxHash (not eth TxHash!) given raw data byte array. The interface may be like: `func ComputeTxHash(bz []byte) (common.Hash, error)`

## Problem Definition

0. To send transactions to evm contracts on okexchain in golang, contract bindings generated through [abigen](https://github.com/ethereum/go-ethereum/tree/master/cmd/abigen) are used: https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L268.  Transactions are sent to rpc server through json-rpc api `eth_sendRawTransaction` [here](https://github.com/ethereum/go-ethereum/blob/76700ac892f6fe3d7865fbe2f724626c72a04227/ethclient/ethclient.go#L527). [`signedTX`](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L271) is returned after sending tx data, with `signedTx.Hash()` to be eth tx hash.

1. okexchaind processes the json rpc request and returns okchainTxhash: https://github.com/okex/okexchain/blob/a6302c78cf/app/rpc/namespaces/eth/api.go#L496

2. To check the status of previous tx (in step 0) using api `eth_getTransactionReceipt`, we need to use okchainTxHash instead of ethTxHash. What we now have is `signedTx` (which is of type github.com/ethereum/go-ethereum/core/types.Transaction), but from our side there's no trivial way to compute okchainTxHash out of it.

3. Some okchain devs mentioned to use the code in  [`handleMsgEthereumTx`](https://github.com/okex/okexchain/blob/a6302c78cf/x/evm/handler.go#L52) to compute okchainTxHash locally in our project, but it involves EVM module config & environment intialization (like what sdk.Context, k *Keeper, chainConfig, etc. do we have to provide?) just to compute the okchainTxHash.

4. Thus from our (okexchaind's application users') point of view, a util / helper function is necessary to compute the okchainTxHash easily and directly. Moreover, we do see some util functions, e.g. [RawTxToEthTx](https://github.com/okex/okexchain/blob/a6302c78cf/app/rpc/types/utils.go#L31) are provided for the ease of developers. So we believe adding such a util function is not very hard but would be helpful work.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
@testrain  Hi~ thanks for your feedback.

We have got your demand for the utils function and it is listed on our schedule. 
Stay tuned for updates please.

**Comment by dryruner** [comment]
Hi @RevelationOfTuring, may I ask when this feature request can be implemented and released? Thank you!

**Comment by RevelationOfTuring** [comment]
> Hi @RevelationOfTuring, may I ask when this feature request can be implemented and released? Thank you!

We plan to add a new utils function in the new gosdk helping to generate hash tx as the one online locally. Thank you for attention.

**Comment by dryruner** [comment]
Hi @RevelationOfTuring,

Can you please instruct us whether this feature has been implemented / released or not? Thank you!

**Comment by deng00** [comment]
it's a big incompatibility of ethereum EVM, lol

**Comment by KamiD** [comment]
the interface of compute exchain tx hash has been supported, plz access the go-sdk to use it~ 
https://github.com/okex/exchain-go-sdk/releases/tag/v0.18.2
