### ISSUE TITLE
eth_getBlockByNumber's output field transactions，it's type is different from etheruem

### ISSUE THREAD

**Issue by ryuuyq** [okx/exchain#786]
### 1. Describe

eth_getBlockByNumber 接口的返回结果，当transactions为空时，

etheruem输出的是`"transactions":[]`，okexchain输出的是`"transactions":null`。

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by KamiD** [comment]
this bug was  already fixed, use the following shell code to test 
```shell
curl https://exchaintest.okexcn.com -X POST  -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b09ea", false],"id":1}'

```

**Comment by liuaiolos** [comment]
> this bug was already fixed, use the following shell code to test
> 
> ```shell
> curl https://exchaintest.okexcn.com -X POST  -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b09ea", false],"id":1}'
> ```

The old blocks still returns null. Need to fix it.

> ```shell
> curl https://exchaintest.okexcn.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x111E1C", false],"id":1}'
> ```

**Comment by KamiD** [comment]
> > this bug was already fixed, use the following shell code to test
> > ```shell
> > curl https://exchaintest.okexcn.com -X POST  -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b09ea", false],"id":1}'
> > ```
> 
> The old blocks still returns null. Need to fix it.
> 
> > ```shell
> > curl https://exchaintest.okexcn.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x111E1C", false],"id":1}'
> > ```

plz wait for the next upgrade of rpc

**Comment by KamiD** [comment]
this issue was fixed
