### ISSUE TITLE
Can not connect to the Mainnet node

### ISSUE THREAD

**Issue by Wangmmx** [okx/exchain#846]
I can not connect to the restful node 'https://www.okex.com' anymore because of this upgrade
What is the new restful node? thanks

**Comment by Wangmmx** [comment]
Maybe some REST apis changed, all I got is 404 error code. The api in this docs can not work https://documenter.getpostman.com/view/1112175/SzS5u6bE?version=latest#fef3e58a-7670-4f1f-8866-b856bb364b51

**Comment by KamiD** [comment]
Plz use the node `https://exchainrpc.okex.org`

for example: https://exchainrpc.okex.org/okexchain/v1/tokens

**Comment by Wangmmx** [comment]
Thank you for your reply!
 I tried to build the node by myself yesterday, and the path is` exchain/v1` can be successful used, are both of these possible? But the path does not work with the node you provided

**Comment by KamiD** [comment]
for now, is okexchain/v1
