### ISSUE TITLE
eth_getFilterChanges error: filter not found

### ISSUE THREAD

**Issue by leoyey** [okx/exchain#852]
使用RPC调用主网（https://exchainrpc.okex.org）的eth_getFilterChanges方法，出现 filter not found。操作步骤如下。请问能否修复一下这个问题？

curl --location --request POST 'https://exchainrpc.okex.org' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_newBlockFilter",
    "params":[],
    "id":128
}'
{"jsonrpc":"2.0","id":128,"result":"0xd5a2f847eb82f05ea65c5a9ee22645b5"}

--------

curl --location --request POST 'https://exchainrpc.okex.org' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_getFilterChanges",
    "params":[
        "0xd5a2f847eb82f05ea65c5a9ee22645b5"
    ],
    "id":128
}'
{"jsonrpc":"2.0","id":128,"error":{"code":-32000,"message":"filter 0xd5a2f847eb82f05ea65c5a9ee22645b5 not found"}}

**Comment by banishee** [comment]
our domain is used in the way of polling strategy, not based on ip from client. 
So your `eth_newBlockFilter ` and `eth_getFilterChanges` requests might be transferred to different nodes.
It is better to use a specific IP instead of domain, and currently we don't provide such a ip.
