### ISSUE TITLE
EmptyUncelHash it not same in Ethereum

### ISSUE THREAD

**Issue by biffyx** [okx/exchain#880]
I ethereum ,the block with EmptyUncalHash will return `types.EmptyUncelHash`

`0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347`

In okexchain, it will return as `common.Hash{}`

`0x0000000000000000000000000000000000000000000000000000000000000000`

So user can't use the `ethereum/go-ethereum/ethclient` in okexchain

**Comment by KamiD** [comment]
thanks for your issue~
