### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by biffyx** [okx/exchain#882]
Version: v0.18.6

panic when websocket request with concurrent

```
panic: concurrent write to websocket connection

goroutine 19652751 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc007929890, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0xad6
github.com/gorilla/websocket.(*messageWriter).Close(0xc007929890, 0x0, 0x0)
        /data/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x85
github.com/gorilla/websocket.(*Conn).beginMessage(0xc00137c2c0, 0xc0012c3e90, 0x1, 0x0, 0x0)
        /data/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:473 +0x71
github.com/gorilla/websocket.(*Conn).NextWriter(0xc00137c2c0, 0x1, 0x0, 0x0, 0x0, 0x0)
        /data/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:513 +0xaa
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc00137c2c0, 0x1f48920, 0xc0012c3e30, 0x0, 0x0)
        /data/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:24 +0x67
github.com/okex/exchain/app/rpc/websockets.(*PubSubAPI).subscribeNewHeads.func1(0xc001a10c60, 0xc0069c9c80, 0xc00263f080, 0xc007d16660, 0xc007d16540)
        /data/.exchaind/exchain/app/rpc/websockets/pubsub_api.go:127 +0xe33
created by github.com/okex/exchain/app/rpc/websockets.(*PubSubAPI).subscribeNewHeads
        /data/.exchaind/exchain/app/rpc/websockets/pubsub_api.go:100 +0x545
```

**Comment by biffyx** [comment]
I find old issue maybe help

https://github.com/gorilla/websocket/issues/119

**Comment by biffyx** [comment]
I think it's a Critical BUG, team should fix it  immediately.
if anyone crawl the exchaind nodes in network which open websocket service, he can make the node panic and offline.

**Comment by banishee** [comment]
@biffyx how many websocket connections did you create to break the node down?

**Comment by biffyx** [comment]
> @biffyx how many websocket connections did you create to break the node down?

1~10 goroutine call `eth_getBlockNumber`, and same number of transactions in each block call `eth_getTransactionReceipt`.

1 goruntine handle pub/sub message.

As not too much transactions in OkChain, i think just concurrent call  `eth_getBlockNumber` will produce this panic.
but same code work fine in ethereum chains.

**Comment by banishee** [comment]
> > @biffyx how many websocket connections did you create to break the node down?
> 
> 1~10 goroutine call `eth_getBlockNumber`, and same number of transactions in each block call `eth_getTransactionReceipt`.
> 
> 1 goruntine handle pub/sub message.
> 
> As not too much transactions in OkChain, i think just concurrent call `eth_getBlockNumber` will produce this panic.
> but same code work fine in ethereum chains.

How often did you reproduce this problem?

**Comment by biffyx** [comment]
my code run well with ethereum chains. on okexchain, it 100% reproduce this problem,  just can't run on this chain.

**Comment by banishee** [comment]
> my code run well with ethereum chains. on okexchain, it 100% reproduce this problem, just can't run on this chain.

Try to compile exchaind with the branch release/v0.18.7.
Check if the panic problem still will show up

**Comment by biffyx** [comment]
> with

new panic when start with new version exchaind

```
I[2021-05-27|23:05:16.409][2379088] starting ABCI with Tendermint                module=main
E[2021-05-27|23:05:18.580][2379088] dialing failed (attempts: 1): dial tcp 3.139.190.170:26656: i/o timeout module=pex addr=765249f3e8c40fd918b0662c67b721344cd409e6@3.139.190.170:26656
E[2021-05-27|23:05:18.580][2379088] dialing failed (attempts: 1): dial tcp 18.192.220.49:26656: i/o timeout module=pex addr=69ea6fb105a3f85d3dd44267d28fae4f0dedf5ab@18.192.220.49:26656
E[2021-05-27|23:05:18.580][2379088] dialing failed (attempts: 1): dial tcp 3.11.47.128:26656: i/o timeout module=pex addr=e83abdf9222dd975dcc5b85d649fa8241797a9b4@3.11.47.128:26656
E[2021-05-27|23:05:18.714][2379088] Corrupted entry. Skipping...                 module=consensus wal=/data/.exchaind/data/cs.wal/wal err="DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]"
E[2021-05-27|23:05:18.858][2379088] data has been corrupted in last height of consensus WAL module=consensus err="DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]" height=3077946
E[2021-05-27|23:05:18.858][2379088] Encountered corrupt WAL file                 module=consensus err="DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]"
E[2021-05-27|23:05:18.858][2379088] Please repair the WAL file before restarting module=consensus
You can attempt to repair the WAL as follows:

----
WALFILE=~/.tendermint/data/cs.wal/wal
cp $WALFILE ${WALFILE}.bak # backup the file
go run scripts/wal2json/main.go $WALFILE > wal.json # this will panic, but can be ignored
rm $WALFILE # remove the corrupt file
go run scripts/json2wal/main.go wal.json $WALFILE # rebuild the file without corruption
----
panic: Failed to start consensus state: DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]

conS:
ConsensusState

conR:
ConsensusReactor

goroutine 139 [running]:
github.com/tendermint/tendermint/consensus.(*Reactor).SwitchToConsensus(0xc000d2bd80, 0xa, 0x0, 0xc000489af6, 0x6, 0xc000489b40, 0xa, 0x2ef739, 0xc001dac860, 0x20, ...)
        /data/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain4/consensus/reactor.go:120 +0x3e8
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00001bd40)
        /data/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain4/blockchain/v0/reactor.go:276 +0x1a88
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /data/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain4/blockchain/v0/reactor.go:118 +0xb0
```

**Comment by biffyx** [comment]
it also have some data errors?

ws request getBlockByNumber bellow， transaction list is empty and `transactionsRoot` is `0x22350d8a0f5ffb64c4be9179292b836d40658e8280d98a7225fdc87b5de6b621`

```
> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x2ee0a2", true],"id":1}
< {"id":1,"jsonrpc":"2.0","result":{"difficulty":"0x0","extraData":"0x","gasLimit":"0xffffffff","gasUsed":"0x0","hash":"0x0c37b8a32310c1847fb5499ea08632d47f099edfcbcb99205985140c0ec6adbd","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x33faa80aa17f6412e8594ed447bad09454a557ac","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x2ee0a2","parentHash":"0x9eb40ed2c5cfe88bd4c0b517074e0928c764e2163339ff26daa1a715216f0d9f","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0xb5a","stateRoot":"0x974ccbe1a0af4569af1c99b01100ef18fc462b1bd81a4d3c0d44966515792fc5","timestamp":"0x60af6183","totalDifficulty":"0x0","transactions":[],"transactionsRoot":"0x22350d8a0f5ffb64c4be9179292b836d40658e8280d98a7225fdc87b5de6b621","uncles":[]}}
```
but the explorer show have transactions

![image](https://user-images.githubusercontent.com/73932585/119861446-fb9fbe00-bf49-11eb-827f-e55c274f7caf.png)


As an empty block,the `transactionsRoot` will  be `0x0000000000000000000000000000000000000000000000000000000000000000`

just like example bellow

```
> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x2ec881", true],"id":1}
< {"id":1,"jsonrpc":"2.0","result":{"difficulty":"0x0","extraData":"0x","gasLimit":"0xffffffff","gasUsed":"0x0","hash":"0x4c58baa275fdf1e592ff9976d2e1eac0e9b6fe8ce11c500233064a54f232c358","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x5304c540ad76fd12bf228c30dc889ad2f80a65fc","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x2ec881","parentHash":"0xbbacb0112b44c9805520d2ccf7e3c9bce2d586445e8d5a17d8ec033359940638","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0xa56","stateRoot":"0xbb8dbd5dac3bcf4857093fcfca6455bdf0031599d8f1d688948c4c0f41f64e9f","timestamp":"0x60af083e","totalDifficulty":"0x0","transactions":[],"transactionsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","uncles":[]}}
```

**Comment by banishee** [comment]
> > with
> 
> new panic when start with new version exchaind
> 
> ```
> I[2021-05-27|23:05:16.409][2379088] starting ABCI with Tendermint                module=main
> E[2021-05-27|23:05:18.580][2379088] dialing failed (attempts: 1): dial tcp 3.139.190.170:26656: i/o timeout module=pex addr=765249f3e8c40fd918b0662c67b721344cd409e6@3.139.190.170:26656
> E[2021-05-27|23:05:18.580][2379088] dialing failed (attempts: 1): dial tcp 18.192.220.49:26656: i/o timeout module=pex addr=69ea6fb105a3f85d3dd44267d28fae4f0dedf5ab@18.192.220.49:26656
> E[2021-05-27|23:05:18.580][2379088] dialing failed (attempts: 1): dial tcp 3.11.47.128:26656: i/o timeout module=pex addr=e83abdf9222dd975dcc5b85d649fa8241797a9b4@3.11.47.128:26656
> E[2021-05-27|23:05:18.714][2379088] Corrupted entry. Skipping...                 module=consensus wal=/data/.exchaind/data/cs.wal/wal err="DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]"
> E[2021-05-27|23:05:18.858][2379088] data has been corrupted in last height of consensus WAL module=consensus err="DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]" height=3077946
> E[2021-05-27|23:05:18.858][2379088] Encountered corrupt WAL file                 module=consensus err="DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]"
> E[2021-05-27|23:05:18.858][2379088] Please repair the WAL file before restarting module=consensus
> You can attempt to repair the WAL as follows:
> 
> ----
> WALFILE=~/.tendermint/data/cs.wal/wal
> cp $WALFILE ${WALFILE}.bak # backup the file
> go run scripts/wal2json/main.go $WALFILE > wal.json # this will panic, but can be ignored
> rm $WALFILE # remove the corrupt file
> go run scripts/json2wal/main.go wal.json $WALFILE # rebuild the file without corruption
> ----
> panic: Failed to start consensus state: DataCorruptionError[failed to read data: EOF (read: 20, wanted: 258)]
> 
> conS:
> ConsensusState
> 
> conR:
> ConsensusReactor
> 
> goroutine 139 [running]:
> github.com/tendermint/tendermint/consensus.(*Reactor).SwitchToConsensus(0xc000d2bd80, 0xa, 0x0, 0xc000489af6, 0x6, 0xc000489b40, 0xa, 0x2ef739, 0xc001dac860, 0x20, ...)
>         /data/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain4/consensus/reactor.go:120 +0x3e8
> github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00001bd40)
>         /data/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain4/blockchain/v0/reactor.go:276 +0x1a88
> created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
>         /data/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain4/blockchain/v0/reactor.go:118 +0xb0
> ```

Maybe you could download a snapshot data to replace the old one. It seems your data was not consistent.

**Comment by banishee** [comment]
![image](https://user-images.githubusercontent.com/48553537/119922234-fcfcd500-bfa1-11eb-97d1-de6282b88e7b.png)

And this is what I queried from official rpc node. Is this result what you expect?

**Comment by biffyx** [comment]
> ![image](https://user-images.githubusercontent.com/48553537/119922234-fcfcd500-bfa1-11eb-97d1-de6282b88e7b.png)
> 
> And this is what I queried from official rpc node. Is this result what you expect?

after upgrade you release v0.18.7.4 ，have the data problem，i don't have expect result, but i think the response is not right result

**Comment by banishee** [comment]
> > ![image](https://user-images.githubusercontent.com/48553537/119922234-fcfcd500-bfa1-11eb-97d1-de6282b88e7b.png)
> > And this is what I queried from official rpc node. Is this result what you expect?
> 
> after upgrade you release v0.18.7.4 ，have the data problem，i don't have expect result, but i think the response is not right result

which part of data do you think is not correct?

**Comment by banishee** [comment]
> > ![image](https://user-images.githubusercontent.com/48553537/119922234-fcfcd500-bfa1-11eb-97d1-de6282b88e7b.png)
> > And this is what I queried from official rpc node. Is this result what you expect?
> 
> after upgrade you release v0.18.7.4 ，have the data problem，i don't have expect result, but i think the response is not right result

I didn't notice that you were testing on the mainnet. The nodes on mainnet still haven'e been upgraded.
May you try to test on the testnet?

**Comment by biffyx** [comment]
> > > ![image](https://user-images.githubusercontent.com/48553537/119922234-fcfcd500-bfa1-11eb-97d1-de6282b88e7b.png)
> > > And this is what I queried from official rpc node. Is this result what you expect?
> > 
> > 
> > after upgrade you release v0.18.7.4 ，have the data problem，i don't have expect result, but i think the response is not right result
> 
> I didn't notice that you were testing on the mainnet. The nodes on mainnet still haven'e been upgraded.
> May you try to test on the testnet?

pls hotfix first.

**Comment by biffyx** [comment]
how is going now  @banishee

**Comment by banishee** [comment]
> > > > ![image](https://user-images.githubusercontent.com/48553537/119922234-fcfcd500-bfa1-11eb-97d1-de6282b88e7b.png)
> > > > And this is what I queried from official rpc node. Is this result what you expect?
> > > 
> > > 
> > > after upgrade you release v0.18.7.4 ，have the data problem，i don't have expect result, but i think the response is not right result
> > 
> > 
> > I didn't notice that you were testing on the mainnet. The nodes on mainnet still haven'e been upgraded.
> > May you try to test on the testnet?
> 
> pls hotfix first.

we don't have plan to upgrade the mainnet yet.
If you really have to do some test on mainnet node, you could have a try to use the v0.18.7.4 version to launch the node.
I think the panic issue has already been fixed in testnet.

**Comment by biffyx** [comment]
My god, you don’t have a mainnet upgrade plan for such a serious problem？
The second case is data problem, I think you should look for the reason and test more.

**Comment by KamiD** [comment]
> My god, you don’t have a mainnet upgrade plan for such a serious problem？
> The second case is data problem, I think you should look for the reason and test more.

after PR #896 has been merged, we will upgrade the rpc node of main-net
