### ISSUE TITLE
怎么在主网部署合约?

### ISSUE THREAD

**Issue by laizy** [okx/exchain#927]
## Summary of Bug

看你们官网喊的口号是：OEC是开放的**去中心化公链**，任何人都可**自由部署项目**；所有用户及开发者都可以免费参与OEC的主网和测试网，不存在收费场景.

但看代码里部署合约有个白名单检查，而且个人账户和部署的项目合约可以随时被平台拉黑。实际试了下普通地址确实无法部署合约，会报`the account 0xxxx is not allowed to deploy a contract`的错误。

所以想问问：
1. 部署合约的流程是什么？需要一个中心化的KYC和审计还是啥？
2. 项目和个人账户被拉黑的规则是怎么样的，是否有一个公示的地方和具体的共识流程，有没有相关的链接？还是就okex说得算？

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by KamiD** [comment]
Now, everyone can feel free to deploy their contract on OEC
