### ISSUE TITLE
 KIP20 token balance via `eth_call` always got zero value

### ISSUE THREAD

**Issue by biffyx** [okx/exchain#930]
get KIP20 token balance via `eth_call` always got zero. the official rpc got correct value.

`
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x382bb369d343125bfb2117af9c149795c6c65c50", "data":"0x70a08231000000000000000000000000F27b7131574dC0C160b21262A383079851B30478"}, "latest"],"id":67}' -H "Content-Type: application/json" http://127.0.0.1:26659
`

`
{"jsonrpc":"2.0","id":67,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"}
`

`
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x382bb369d343125bfb2117af9c149795c6c65c50", "data":"0x70a08231000000000000000000000000F27b7131574dC0C160b21262A383079851B30478"}, "latest"],"id":67}' -H "Content-Type: application/json" https://exchainrpc.okex.org
`

`
{"jsonrpc":"2.0","id":67,"result":"0x000000000000000000000000000000000000000000000f614dd7cd679ae06613"}
`

**Comment by scream7** [comment]
simillar issuse, I got result "0x00000000000000000000000000000000000000000000000000054f0f4fa70107" no matter which account I called, But I got correct answer while called https://exchainrpc.okex.org node

**Comment by scream7** [comment]
> simillar issuse, I got result "0x00000000000000000000000000000000000000000000000000054f0f4fa70107" no matter which account I called, But I got correct answer while called https://exchainrpc.okex.org node

just upgraded to 1.8.10 and it works

**Comment by banishee** [comment]
it is better to upgrade exchaind into the latest version, we fix a few rpc bugs recently.
And if you use the outdated exchaind to sync blocks from mainnet or testnet, try to delelte `./data/watch.db`, then reboot node
