### ISSUE TITLE
Synching speed is too slow

### ISSUE THREAD

**Issue by xiaoxuez** [okx/exchain#937]
I download snapshot 7.29 at 8.1, now is 8.3, but node is still behind mainnet.

The machine's indicators are 4-core CPU over 100% and memory 2.5%. Whether the type of ssd can affect the synchronization speed，does it need nvme?

My config: pruning = nothing && fastsync = true

**Comment by banishee** [comment]
there is the doc about recommended configuration
https://forum.okt.club/d/25

**Comment by banishee** [comment]
If you still have issues with that, reopen this issue
