### ISSUE TITLE
how are the same gas sorted? exchaind

### ISSUE THREAD

**Issue by myuniswap2000** [okx/exchain#978]
Hello admin and everyone, 
1, how are the same gas sorted, exchaind?
2, Is it according to the machines that arrive at the miners first?
thank you !

**Comment by banishee** [comment]
> Hello admin and everyone,
> 1, how are the same gas sorted, exchaind?
> 2, Is it according to the machines that arrive at the miners first?
> thank you !

if the gasprice are same among txs, it will sort them base on timestamp of its arrival.

**Comment by myuniswap2000** [comment]
thank you !
