### ISSUE TITLE
Sync always automatically stopped after catching up very close to current tip

### ISSUE THREAD

**Issue by nining** [okx/exchain#980]
### 1. Describe
Sync always automatically stopped after catching up very close to current tip.

### 2. Impact
The node would never catch up the latest block.  I have to timely restart the node to let it catch up as closely as possible.

## Version

form 0.18.16 to 0.18.18
Ubuntu 20.04.2 LTS
Linux node1 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nining** [comment]
I found a workaround solution:

Open the config.toml file and change the following value to false:

fast_sync = false

**Comment by banishee** [comment]
https://github.com/okex/exchain/tree/fix-p2p-hang
Maybe have a try on this branch, though not released
